<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TermsAndConditionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $sections = [
            ['INTRODUCTION', "UniAds is a dedicated online platform created to facilitate meaningful connections between students and higher education institutions across Sri Lanka. Our platform serves as a comprehensive information hub, enabling students to explore a wide range of degree, diploma, and postgraduate programs, while allowing institutions to share accurate and timely information regarding their courses, events, and updates.\r\n\r\nBy accessing or using UniAds, you explicitly acknowledge that you have read, understood, and agree to be bound by these Terms & Conditions (“Terms”). Your continued use of the platform constitutes your acceptance of these Terms. It is essential that all users review these Terms carefully before engaging with the platform, as they govern the legal rights and obligations associated with the use of UniAds.\r\n\r\nThese Terms apply to all users of UniAds, including but not limited to students, educational institutions, and any authorized representatives of institutions or third-party entities who access or interact with the platform. Whether you are registering as a student, managing an institutional profile, or engaging with UniAds in any other capacity, you are subject to these Terms.\r\n\r\nUse of UniAds is strictly conditional upon your acceptance of these Terms. Any access, registration, or engagement with the platform implies your agreement to comply with all provisions set forth herein. Users who do not agree with these Terms are not permitted to access or use UniAds and must refrain from creating an account or interacting with any part of the platform. UniAds reserves the right to restrict or terminate access to any user who fails to comply with these Terms.", 1],
            ['ELIGIBILITY', "UniAds is designed to serve both students and recognized educational institutions in Sri Lanka. To ensure the integrity, safety, and lawful use of the platform, all users must meet certain eligibility requirements. UniAds reserves the right to verify, approve, or refuse any account based on these criteria.\r\n\r\n𝟏. 𝐌𝐢𝐧𝐢𝐦𝐮𝐦 𝐀𝐠𝐞 𝐑𝐞𝐪𝐮𝐢𝐫𝐞𝐦𝐞𝐧𝐭 𝐟𝐨𝐫 𝐒𝐭𝐮𝐝𝐞𝐧𝐭𝐬:\r\nStudents must be at least 18 years old to independently create and use a UniAds account. Users under 18 may access the platform only with verifiable consent from a legal guardian. This requirement ensures that all users have the legal capacity to enter into agreements and interact responsibly on the platform.\r\n\r\n𝟐. 𝐈𝐧𝐬𝐭𝐢𝐭𝐮𝐭𝐢𝐨𝐧 𝐑𝐞𝐠𝐢𝐬𝐭𝐫𝐚𝐭𝐢𝐨𝐧 𝐚𝐧𝐝 𝐑𝐞𝐜𝐨𝐠𝐧𝐢𝐭𝐢𝐨𝐧:\r\nEducational institutions must be formally registered and recognized under Sri Lankan educational regulations. Only institutions that meet these legal and operational standards are permitted to create accounts and promote courses on UniAds. This requirement safeguards students from fraudulent or unverified organizations.\r\n\r\n𝟑. 𝐔𝐬𝐞𝐫 𝐈𝐝𝐞𝐧𝐭𝐢𝐭𝐲 𝐚𝐧𝐝 𝐀𝐮𝐭𝐡𝐨𝐫𝐢𝐭𝐲:\r\nAll users representing institutions must confirm their identity and have the legal authority to act on behalf of the institution. This includes administrators, course coordinators, or authorized staff members who manage institutional profiles, posts, and subscriptions. Providing accurate and truthful information is mandatory.\r\n\r\n𝟒. 𝐑𝐢𝐠𝐡𝐭 𝐭𝐨 𝐑𝐞𝐟𝐮𝐬𝐞 𝐨𝐫 𝐓𝐞𝐫𝐦𝐢𝐧𝐚𝐭𝐞 𝐀𝐜𝐜𝐨𝐮𝐧𝐭𝐬:\r\nUniAds reserves the right to refuse account registration or to suspend/terminate existing accounts if the eligibility criteria are not met, if the information provided is false, or if the user or institution fails to comply with applicable laws and regulations. This ensures a safe and trustworthy environment for all users.", 2],
            ['USER ACCOUNTS', "Creating and maintaining an account on UniAds allows both students and institutions to access the platform’s full features, including course browsing, applications, content posting, and subscription management. To ensure platform security and integrity, users must adhere to account-related responsibilities.\r\n\r\n● 𝐀𝐜𝐜𝐨𝐮𝐧𝐭 𝐂𝐫𝐞𝐚𝐭𝐢𝐨𝐧 𝐚𝐧𝐝 𝐕𝐞𝐫𝐢𝐟𝐢𝐜𝐚𝐭𝐢𝐨𝐧:\r\nTo register, users must provide a valid email address, create a secure password, and complete any verification steps required by UniAds. Verification may include  additional identity checks for institutional representatives. This process ensures that only legitimate users gain access.\r\n\r\n● 𝐀𝐜𝐜𝐮𝐫𝐚𝐜𝐲 𝐨𝐟 𝐈𝐧𝐟𝐨𝐫𝐦𝐚𝐭𝐢𝐨𝐧:\r\nUsers are obligated to provide accurate and up-to-date information at all times. This includes personal details for students and institutional data for organizations. Maintaining accurate information facilitates smooth communication and proper functionality of UniAds services.\r\n\r\n● 𝐂𝐨𝐧𝐟𝐢𝐝𝐞𝐧𝐭𝐢𝐚𝐥𝐢𝐭𝐲 𝐨𝐟 𝐋𝐨𝐠𝐢𝐧 𝐃𝐞𝐭𝐚𝐢𝐥𝐬:\r\nEach user is responsible for keeping their account credentials confidential. Sharing login details with unauthorized parties is strictly prohibited. UniAds cannot be held responsible for unauthorized access resulting from negligence in protecting account credentials.\r\n\r\n● 𝐂𝐨𝐧𝐬𝐞𝐪𝐮𝐞𝐧𝐜𝐞𝐬 𝐨𝐟 𝐌𝐢𝐬𝐮𝐬𝐞:\r\nAny misuse of accounts including fraudulent activity, impersonation, or repeated policy violations may result in account suspension or termination. UniAds reserves the right to take appropriate action to protect the community and enforce compliance with its Terms.", 3],
            ['USER CONDUCT', "UniAds is committed to providing a safe, professional, and educational environment for all users. Maintaining respectful and lawful behavior on the platform is essential for protecting the integrity of the services and ensuring a positive experience for both students and institutions.\r\n\r\n𝟏. 𝐑𝐞𝐬𝐩𝐞𝐜𝐭𝐟𝐮𝐥 𝐔𝐬𝐞:\r\nAll users are expected to interact respectfully with others and to use UniAds solely for lawful and educational purposes. Harassment, discrimination, or any offensive behavior is strictly prohibited.\r\n\r\n𝟐. 𝐏𝐫𝐨𝐡𝐢𝐛𝐢𝐭𝐞𝐝 𝐂𝐨𝐧𝐭𝐞𝐧𝐭 𝐚𝐧𝐝 𝐀𝐜𝐭𝐢𝐯𝐢𝐭𝐲:\r\nUsers must not post fake, misleading, or deceptive course information. Additionally, uploading content that is abusive, offensive, or violates third-party rights is strictly forbidden. UniAds also prohibits the use of automated bots, scraping tools, or any activity that interferes with the platform’s normal operations.\r\n\r\n𝟑. 𝐒𝐞𝐜𝐮𝐫𝐢𝐭𝐲 𝐚𝐧𝐝 𝐒𝐲𝐬𝐭𝐞𝐦 𝐈𝐧𝐭𝐞𝐠𝐫𝐢𝐭𝐲:\r\nAttempts to hack, disrupt, or manipulate UniAds’ systems or data are strictly forbidden. Users engaging in such activities may face immediate account suspension and potential legal consequences.\r\n\r\n𝟒. 𝐏𝐥𝐚𝐭𝐟𝐨𝐫𝐦 𝐄𝐧𝐟𝐨𝐫𝐜𝐞𝐦𝐞𝐧𝐭:\r\nUniAds reserves the right to review content and user activity. The platform may remove any content deemed inappropriate or in violation of these Terms and block accounts when necessary to maintain compliance and community standards.", 4],
            ['CONTENT & INTELLECTUAL PROPERTY', "UniAds respects the intellectual property rights of all users and institutions while safeguarding its own proprietary content. All content uploaded to the platform is subject to these guidelines to ensure clarity regarding ownership, usage, and protection.\r\n\r\n● 𝐎𝐰𝐧𝐞𝐫𝐬𝐡𝐢𝐩 𝐨𝐟 𝐔𝐩𝐥𝐨𝐚𝐝𝐞𝐝 𝐂𝐨𝐧𝐭𝐞𝐧𝐭:\r\nUsers and institutions retain full ownership of any content they upload to UniAds, including course descriptions, events, posts, reviews, and other materials. By uploading content, users confirm that they have the legal right to share it and that it does not infringe on the rights of any third party.\r\n\r\n● 𝐋𝐢𝐜𝐞𝐧𝐬𝐞 𝐭𝐨 𝐔𝐧𝐢𝐀𝐝𝐬:\r\nBy using UniAds, users grant the platform a non-exclusive, worldwide, royalty-free license to display, host, store, and distribute their content solely for the purpose of providing and promoting the platform’s services. This license allows UniAds to make the content visible to other users and facilitates the platform’s core functionality, including search, display, and promotion of courses and events.\r\n\r\n● 𝐏𝐫𝐨𝐭𝐞𝐜𝐭𝐢𝐨𝐧 𝐨𝐟 𝐔𝐧𝐢𝐀𝐝𝐬 𝐂𝐨𝐧𝐭𝐞𝐧𝐭:\r\nAll content, branding, design, logos, and intellectual property created by UniAds are protected under copyright and trademark laws. Users are prohibited from copying, reproducing, or distributing UniAds’ proprietary content without express written permission.\r\n\r\n● 𝐇𝐚𝐧𝐝𝐥𝐢𝐧𝐠 𝐂𝐨𝐩𝐲𝐫𝐢𝐠𝐡𝐭 𝐕𝐢𝐨𝐥𝐚𝐭𝐢𝐨𝐧𝐬:\r\nUniAds has procedures in place to address intellectual property infringements. Users or rights holders may submit formal removal requests if they believe their copyrighted material is used without authorization. UniAds reserves the right to remove content, suspend accounts, or take other necessary actions to protect intellectual property rights.", 5],
            ['PLATFORM USE', "UniAds is designed to facilitate meaningful connections between students and higher education institutions across Sri Lanka. The platform provides a suite of tools to help students discover academic opportunities and for institutions to share their offerings effectively.\r\n\r\nStudents can explore courses, diplomas, and postgraduate programs, browse posts and events, and interact with information provided by institutions. The platform allows for convenient searching, filtering by course type, duration, and location, and staying updated on new offerings or announcements. By using these tools, students gain comprehensive visibility into educational opportunities without leaving the platform.\r\n\r\nInstitutions, on the other hand, can create posts to showcase courses, manage their dashboard to monitor performance, and access premium features that offer analytics, subscription management, and enhanced visibility. The platform encourages institutions to use these tools solely for educational promotion and communication with prospective students.\r\n\r\n● 𝐏𝐞𝐫𝐦𝐢𝐭𝐭𝐞𝐝 𝐔𝐬𝐞𝐬:\r\n - Posting courses, events, and academic updates.\r\n - Engaging with students for educational purposes.\r\n - Leveraging dashboard analytics and premium features responsibly.\r\n\r\n● 𝐏𝐫𝐨𝐡𝐢𝐛𝐢𝐭𝐞𝐝 𝐔𝐬𝐞𝐬:\r\nUsers must not exploit UniAds for activities unrelated to academic promotion, including commercial advertising outside educational offerings, spamming, or any actions that disrupt the platform’s functionality.\r\n\r\nUniAds operates purely as an information-sharing platform and does not guarantee admission, enrollment, or academic outcomes. Students should independently verify details with institutions before making decisions, and institutions must ensure the accuracy of the content they post.", 6],
            ['PAYMENT & SUBSCRIPTIONS', "UniAds offers premium subscription plans specifically designed for institutions seeking enhanced visibility, analytics, and advanced management features on the platform. These subscriptions provide access to additional tools such as follower tracking, post performance analytics, and the ability to integrate posts with external social platforms.\r\n\r\nTo ensure secure transactions, all payments are processed through a certified payment gateway accepted in Sri Lanka. This gateway employs advanced encryption protocols, PCI DSS 4.0 compliance, and robust fraud prevention systems, guaranteeing that sensitive payment information is protected at all times.\r\n\r\n● 𝐓𝐫𝐢𝐚𝐥 𝐚𝐧𝐝 𝐒𝐮𝐛𝐬𝐜𝐫𝐢𝐩𝐭𝐢𝐨𝐧 𝐒𝐭𝐫𝐮𝐜𝐭𝐮𝐫𝐞:\r\nInstitutions are eligible for a one-time free trial, allowing them to experience premium features before committing to a paid plan. Following the trial period, billing begins according to the selected cycle monthly or annually. Renewal of subscriptions occurs automatically unless explicitly canceled prior to the next billing cycle.\r\n\r\n● 𝐂𝐚𝐧𝐜𝐞𝐥𝐥𝐚𝐭𝐢𝐨𝐧𝐬 𝐚𝐧𝐝 𝐅𝐚𝐢𝐥𝐞𝐝 𝐏𝐚𝐲𝐦𝐞𝐧𝐭𝐬:\r\nInstitutions may cancel their subscription at any time. If a payment fails, access to premium features may be suspended until the payment is successfully completed. UniAds does not allow repeated free trials; each institution can only access the trial once to maintain fairness and system integrity. Refunds, if applicable, are subject to the policies outlined during the subscription process and in accordance with applicable consumer protection laws.\r\n\r\nBy subscribing, institutions acknowledge and agree to adhere to these payment rules and understand that premium features are contingent upon successful payment and compliance with UniAds’ terms.", 7],
            ['LIABILITY & DISCLAIMERS', "UniAds is committed to providing accurate and up-to-date information to facilitate connections between students and higher education institutions in Sri Lanka. However, the platform acts solely as an information and promotion tool and does not guarantee the accuracy, completeness, or reliability of course details or claims made by institutions.\r\n\r\nWhile using UniAds, users acknowledge and agree that the platform, its operators, and affiliated personnel cannot be held liable for certain outcomes, including but not limited to:\r\n\r\n● 𝐀𝐝𝐦𝐢𝐬𝐬𝐢𝐨𝐧 𝐨𝐮𝐭𝐜𝐨𝐦𝐞𝐬: UniAds does not influence or guarantee student admission into any institution.\r\n\r\n● 𝐂𝐨𝐧𝐭𝐞𝐧𝐭 𝐚𝐜𝐜𝐮𝐫𝐚𝐜𝐲: Institutions are responsible for the correctness of the information they upload. UniAds is not liable for any inaccuracies, omissions, or misleading content.\r\n\r\n● 𝐏𝐥𝐚𝐭𝐟𝐨𝐫𝐦 𝐚𝐯𝐚𝐢𝐥𝐚𝐛𝐢𝐥𝐢𝐭𝐲 𝐚𝐧𝐝 𝐩𝐞𝐫𝐟𝐨𝐫𝐦𝐚𝐧𝐜𝐞: The platform may occasionally experience downtime, technical errors, or bugs that could affect access or functionality.\r\n\r\nBy using UniAds, users acknowledge these limitations and agree to hold the platform harmless from any claims, losses, or damages arising from the above scenarios.", 8],
            ['TERMINATION & ACCOUNT DELETION', "UniAds reserves the right to manage user accounts in accordance with these Terms, ensuring a safe and reliable platform for all users. Account termination and deletion policies vary depending on whether the user is a student or an institution.\r\n\r\nStudents have the ability to delete their accounts directly through the platform. This process allows them to permanently remove their personal information, activity history, and any associated data. Once a student account is deleted:\r\n● All personal and activity data is permanently removed from UniAds systems.\r\n● Any premium features or subscriptions linked to the account are immediately terminated.\r\n● Deleted data cannot be recovered under any circumstances.\r\n\r\nInstitutions must contact UniAds administration to request account deletion. Upon approval:\r\n● All institutional data, including profiles, posts, and activity records, is completely removed.\r\n● Any active premium subscriptions are canceled immediately.\r\n● Deleted institutional accounts cannot be restored, ensuring full compliance with data protection and privacy standards.\r\n\r\nUniAds retains the right to suspend or terminate accounts both student and institutional if there is evidence of policy violations, misuse of the platform, or behavior that threatens the integrity of the service. Users are responsible for complying with the Terms, and failure to do so may result in permanent account termination.", 9],
            ['GOVERNING LAW & DISPUTE RESOLUTION', "These Terms are governed by and interpreted in accordance with the laws of Sri Lanka. By using UniAds, users agree to comply with all applicable local laws and regulations, ensuring responsible and lawful use of the platform.\r\n\r\nIn the event of a disagreement or dispute arising from the use of UniAds, the following steps should be taken:\r\n\r\n● 𝐃𝐢𝐫𝐞𝐜𝐭 𝐑𝐞𝐬𝐨𝐥𝐮𝐭𝐢𝐨𝐧: Users are encouraged to first attempt to resolve any issues directly with UniAds support. Contacting support promptly can help clarify concerns or address misunderstandings.\r\n\r\n● 𝐋𝐞𝐠𝐚𝐥 𝐑𝐞𝐬𝐨𝐥𝐮𝐭𝐢𝐨𝐧: If the dispute cannot be resolved informally, any unresolved matters will be subject to the exclusive jurisdiction of courts in Sri Lanka. Users agree to submit to the courts in Sri Lanka for resolution of any legal claims arising from these Terms or the use of the platform.\r\n\r\nUniAds emphasizes the importance of complying with all Sri Lankan laws while using the service, including regulations related to data protection, intellectual property, and online conduct. Users acknowledge that adherence to these laws is a fundamental condition for accessing and using the platform.", 10],
        ];

        foreach ($sections as $section) {
            DB::table('terms_and_conditions')->updateOrInsert(
                ['title' => $section[0]],
                [
                    'content' => $section[1],
                    'order_index' => $section[2],
                    'updated_at' => now(),
                    'created_at' => now(),
                ]
            );
        }
    }
}
